# Generated by Django 5.0.4 on 2024-04-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='charactor_promt',
            field=models.TextField(blank=True),
        ),
    ]
