# Generated by Django 5.0.4 on 2024-04-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_character_charactor_promt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='title',
            new_name='description',
        ),
    ]
