# Generated by Django 5.0.4 on 2024-04-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_character_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='charactor_promt',
        ),
    ]
