# Generated by Django 5.0.4 on 2024-04-20 05:54

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_character_charactor_promt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.CharField(default=builtins.dir, max_length=50),
            preserve_default=False,
        ),
    ]
