# Generated by Django 5.0.4 on 2024-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_category_options_character_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='prompt_instruction',
            field=models.TextField(blank=True),
        ),
    ]
